-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2019-01-13 16:57:33 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE SEQUENCE ID_KAT_SEKW START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1 ;
  GRANT ALL PRIVILEGES ON ID_KAT_SEKW TO BD2A07_APP ;
  GRANT ALL PRIVILEGES ON ID_KAT_SEKW TO BD2A07 ;

CREATE SEQUENCE ID_PAR_WYG_STR_SEKW START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1 ;
  GRANT ALL PRIVILEGES ON ID_PAR_WYG_STR_SEKW TO BD2A07 ;
  GRANT ALL PRIVILEGES ON ID_PAR_WYG_STR_SEKW TO BD2A07_APP ;

CREATE SEQUENCE NR_UZYT_SEKW START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 ;
  GRANT ALL PRIVILEGES ON NR_UZYT_SEKW TO BD2A07 ;
  GRANT ALL PRIVILEGES ON NR_UZYT_SEKW TO BD2A07_APP ;







CREATE OR REPLACE TRIGGER ID_KAT_TRG 
    BEFORE INSERT ON KATEGORIE 
    FOR EACH ROW 
    WHEN ( NEW.ID_KATEGORII IS NULL ) 
SELECT ID_KAT_SEKW.NEXTVAL INTO :NEW.ID_KATEGORII FROM dual; 
/



CREATE OR REPLACE TRIGGER ID_PAR_WYG_STR_TRG 
    BEFORE INSERT ON PARAMETRY_WYGLADU_STR 
    FOR EACH ROW 
    WHEN ( NEW.ID_PARAMETRU IS NULL ) 
SELECT ID_PAR_WYG_STR_SEKW.NEXTVAL INTO :NEW.ID_PARAMETRU FROM dual ;
/



CREATE OR REPLACE TRIGGER NR_UZYT_TRG 
    BEFORE INSERT ON UZYTKOWNICY 
    FOR EACH ROW 
    WHEN ( NEW.NUMER_UZYTKOWNIKA IS NULL ) 
SELECT NR_UZYT_SEKW.NEXTVAL INTO :NEW.NUMER_UZYTKOWNIK FROM dual; 
/




-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             0
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
