-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2019-01-13 16:56:15 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g










CREATE OR REPLACE SYNONYM BD2A07_APP.DZIENNIKI_AKTYWNOSCI FOR DZIENNIKI_AKTYWNOSCI ;

CREATE OR REPLACE SYNONYM BD2A07_APP.KATEGORIE FOR KATEGORIE ;

CREATE OR REPLACE SYNONYM BD2A07_APP.KAT_INTERESUJACE_UZYT FOR KAT_INTERESUJACE_UZYT ;

CREATE OR REPLACE SYNONYM BD2A07_APP.PARAMETRY_UZYT FOR PARAMETRY_UZYT ;

CREATE OR REPLACE SYNONYM BD2A07_APP.PARAMETRY_WYGLADU_STR FOR PARAMETRY_WYGLADU_STR ;

CREATE OR REPLACE SYNONYM BD2A07_APP.UZYTKOWNICY FOR UZYTKOWNICY ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             0
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           6
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
